const jwt = require("jwt-simple");
const User = require("../models/users");
const config = require("../config");

function tokenForUser(user) {
  const timestamp = new Date().getTime();
  // Here id is the one which is auto generated by MongoDB.
  return jwt.encode({ sub: user.id, iat: timestamp }, config.secret);
}

exports.signup = function(req, res, next) {
  const email = req.body.email;
  const password = req.body.password;

  if (!email || !password) {
    return res
      .status(422)
      .send({ error: "You must provide email and password" });
  }

  //See if a user with the given email exist
  // User represents all Users
  //First parameter is the search criteria second one is the callback function
  User.findOne({ email: email }, function(err, existingUser) {
    // existingUser will be null if no user found.
    if (err) {
      return next(err);
    }
    // If a user with email does exist, return an error
    if (existingUser) {
      return res.status(422).send({ error: "Email is in use" });
    }
    //If not create and save the record
    const user = new User({
      email: email,
      password: password
    });

    user.save(function(err) {
      if (err) {
        return next(err);
      }
      res.json({ token: tokenForUser(user) });
    });
  });
  //respond to request indictaing user was created.
};

exports.signin = function(req, res, next) {
  //User has already had their email and pwd auth'd just give them a token
  res.send({ token: tokenForUser(req.user) });
};
